### ISSUE TITLE
dell optiplex 3000 

### ISSUE THREAD

**Issue by ghost** [AaronKelley/DellFanManagement#34]
Is there a way to make it work on the Dell Optiplex 3000? It is always giving me the same revolutions: 
![image](https://github.com/AaronKelley/DellFanManagement/assets/105122940/d6bb0160-c872-4991-a80b-65d2ab7b56ce)

**Comment by AaronKelley** [comment]
It looks like Optiplex 3000 is a 2022 (12th-gen) system?  This fan control method only works with Dell systems released before 2021 (10th-gen and earlier).

**Comment by techjaw** [comment]
Hello and, above all, thank you for the great work you have shared with us on various forums. Like you, I have been a supporter of Dell for over a dozen years, mainly XPS (the best equipment I have ever had), and now I have a Vostro 5630 and the behavior of the fans is unacceptable, especially on battery power. I have been an IT specialist for 25 years, but I gave up when it comes to controlling fans in 13th generation Dells. Additionally, the 1360P doesn't quite cope with thermals. So the question for you is whether you have a way to control the fan in any way. I've probably tested everything that could help. I limited the power and clock speed to a minimum so that the battery wouldn't make too much noise. Of course, new toothpaste, etc. I came to the conclusion that I can only achieve the effect in two ways. Either I will build a PWM modulator and connect it between the board and the fan (4 pins) or I will use a bus programmer and block what is needed. The warranty doesn't matter to me. Do I have any experience, documentation, links about my two ideas? Thank you in advance for any help. In desperation, I disconnected the fan for a long time, experienced silence and the temperature oscillated between 70 degrees C and a maximum of 95 degrees C. I even thought about an independent fan control system, a PWM module + thermistor powered from USB or something else. However, I have to "fool" the board that the fan is connected, but I don't know how yet.

**Comment by AaronKelley** [comment]
I have not had any new leads on a way to control fans on a system with 11th-gen CPU or later.  If anyone figures it out (Windows or Linux), then I will take a stab at adding support for this tool.

Clearly it is possible.  The Dell self-diagnostics program has a fan check and during that check it sets the speed to a few different levels.  The best idea I have is to take a BIOS dump, disassemble it, and figure out what it is doing to mess with the fans there.  But, I do not have the expertise required to do that.

Hardware solutions are possible.  The fans are connected with four wires and one of them is used for PWM control, so you could "intercept" that signal and change it to your liking.  That's not something I am interested in messing with, either, seems like it would be a pain to adapt for each new system.  (Dell is even known to change the fan pinout between systems.  Dell Precision M6700 and Dell Precision M6800 have the same fan connector but a different pinout; you can't use a fan from one system in the other without rearranging the wires.)

The only Dell laptop that I am using regularly now is a Precision 7560 with 11th-gen CPU.  The auto fan control in this system is adequate but it seems slowly to be getting noisier over time.  On my personal system, I have switched to a MacBook Pro, and I love this one as least as far as fan behavior goes.  It actually runs with the fans completely off for office-type workloads and yet it is still totally cool to the touch, unlike my Dell Precisions which must run with the fans on even on an idle workload with turbo boost disabled, and even then they are like little space heaters with a warm keyboard.

**Comment by techjaw** [comment]
Thank you for the info, I know that two pins power the fan, one by generating a square wave signal controls the speed, the more peaks per unit of time, the faster the fan rotates. The fourth one contains information about the fan speed. By intercepting the signal, it could be modified and I think I will go in that direction. Then I can modify the revolutions controlled by the PWM generator in each system. I will let you know what I achieved for posterity. I will connect an oscilloscope at work and check the signal.

**Comment by Some1sm** [comment]
Hey Aaron we own hundreds of Latitude's 3440 in our office, if you need a BIOS or whatever just let me know I will literally print your pfp and pay respects daily in the office. The noise is killing me and all DELL fan curves seem to be broken.
